const frechWords = [
    { front: "bonjour", back: "hello" },
    { front: "au revoir", back: "goodbye" },
    { front: "merci", back: "thank you" },
    { front: "s'il vous plaît", back: "please" },
    { front: "oui", back: "yes" },
    { front: "non", back: "no" },
    { front: "amour", back: "love" },
    { front: "faim", back: "hunger" },
    { front: "peur", back: "fear" },
    { front: "pain", back: "bread" },
    { front: "fromage", back: "cheese" },
    { front: "eau", back: "water" },
    { front: "feu", back: "fire" },
    { front: "terre", back: "earth" },
    { front: "vent", back: "wind" },
    { front: "temps", back: "time" },
    { front: "jour", back: "day" },
    { front: "nuit", back: "night" },
    { front: "lumière", back: "light" },
    { front: "ombre", back: "shadow" },
    { front: "ami", back: "friend" },
    { front: "famille", back: "family" },
    { front: "maison", back: "house" },
    { front: "école", back: "school" },
    { front: "travail", back: "work" },
    { front: "argent", back: "money" },
    { front: "père", back: "father" },
    { front: "mère", back: "mother" },
    { front: "frère", back: "brother" },
    { front: "sœur", back: "sister" },
    { front: "chien", back: "dog" },
    { front: "chat", back: "cat" },
    { front: "oiseau", back: "bird" },
    { front: "cheval", back: "horse" },
    { front: "vélo", back: "bicycle" },
    { front: "voiture", back: "car" },
    { front: "bus", back: "bus" },
    { front: "train", back: "train" },
    { front: "avion", back: "airplane" },
    { front: "bateau", back: "boat" },
    { front: "manger", back: "to eat" },
    { front: "boire", back: "to drink" },
    { front: "dormir", back: "to sleep" },
    { front: "parler", back: "to speak" },
    { front: "écouter", back: "to listen" },
    { front: "voir", back: "to see" },
    { front: "regarder", back: "to watch" },
    { front: "marcher", back: "to walk" },
    { front: "courir", back: "to run" },
    { front: "lire", back: "to read" },
    { front: "écrire", back: "to write" },
    { front: "acheter", back: "to buy" },
    { front: "vendre", back: "to sell" },
    { front: "aimer", back: "to love" },
    { front: "détester", back: "to hate" },
    { front: "attendre", back: "to wait" },
    { front: "commencer", back: "to begin" },
    { front: "finir", back: "to finish" },
    { front: "apprendre", back: "to learn" },
    { front: "comprendre", back: "to understand" },
    { front: "savoir", back: "to know" },
    { front: "voir", back: "to see" },
    { front: "demander", back: "to ask" },
    { front: "répondre", back: "to answer" },
    { front: "donner", back: "to give" },
    { front: "recevoir", back: "to receive" },
    { front: "devoir", back: "to must" },
    { front: "pouvoir", back: "to be able to" },
    { front: "vouloir", back: "to want" },
    { front: "changer", back: "to change" },
    { front: "rester", back: "to stay" },
    { front: "partir", back: "to leave" },
    { front: "entrer", back: "to enter" },
    { front: "sortir", back: "to go out" },
    { front: "vivre", back: "to live" },
    { front: "mourir", back: "to die" },
    { front: "travailler", back: "to work" },
    { front: "dormir", back: "to sleep" },
    { front: "se lever", back: "to get up" },
    { front: "se coucher", back: "to go to bed" },
    { front: "se laver", back: "to wash" },
    { front: "se habiller", back: "to dress" },
    { front: "s'asseoir", back: "to sit" },
    { front: "se lever", back: "to stand up" },
    { front: "se reposer", back: "to rest" },
    { front: "se détendre", back: "to relax" },
    { front: "penser", back: "to think" },
    { front: "comprendre", back: "to understand" },
    { front: "chercher", back: "to search" },
    { front: "trouver", back: "to find" },
    { front: "perdre", back: "to lose" },
    { front: "gagner", back: "to win" },
    { front: "gagner", back: "to earn" },
    { front: "se souvenir", back: "to remember" },
    { front: "oublier", back: "to forget" },
    { front: "savoir", back: "to know" },
    { front: "comprendre", back: "to understand" },
    { front: "trouver", back: "to find" },
    { front: "avoir", back: "to have" },
    { front: "être", back: "to be" },
    { front: "faire", back: "to do" },
    { front: "dire", back: "to say" },
    { front: "aller", back: "to go" },
    { front: "venir", back: "to come" },
    { front: "prendre", back: "to take" },
    { front: "donner", back: "to give" },
    { front: "voir", back: "to see" },
    { front: "sentir", back: "to feel" },
    { front: "parler", back: "to speak" },
    { front: "entendre", back: "to hear" },
    { front: "toucher", back: "to touch" },
    { front: "regarder", back: "to look at" },
    { front: "écouter", back: "to listen" },
    { front: "regarder", back: "to watch" },
    { front: "aider", back: "to help" },
    { front: "aimer", back: "to like" },
    { front: "travailler", back: "to work" },
    { front: "dormir", back: "to sleep" },
    { front: "lire", back: "to read" },
    { front: "écrire", back: "to write" },
    { front: "marcher", back: "to walk" },
    { front: "courir", back: "to run" },
    { front: "sauter", back: "to jump" },
    { front: "nager", back: "to swim" },
    { front: "voler", back: "to fly" },
    { front: "trouver", back: "to find" },
    { front: "perdre", back: "to lose" },
    { front: "gagner", back: "to win" },
    { front: "cuisiner", back: "to cook" },
    { front: "nettoyer", back: "to clean" },
    { front: "réparer", back: "to fix" },
    { front: "construire", back: "to build" },
    { front: "détruire", back: "to destroy" },
    { front: "grand", back: "big" },
    { front: "petit", back: "small" },
    { front: "long", back: "long" },
    { front: "court", back: "short" },
    { front: "haut", back: "high" },
    { front: "bas", back: "low" },
    { front: "large", back: "wide" },
    { front: "étroit", back: "narrow" },
    { front: "fort", back: "strong" },
    { front: "faible", back: "weak" },
    { front: "beau", back: "beautiful" },
    { front: "laid", back: "ugly" },
    { front: "jeune", back: "young" },
    { front: "vieux", back: "old" },
    { front: "rapide", back: "fast" },
    { front: "lent", back: "slow" },
    { front: "chaud", back: "hot" },
    { front: "froid", back: "cold" },
    { front: "facile", back: "easy" },
    { front: "difficile", back: "difficult" },
    { front: "téléphone", back: "phone" },
    { front: "internet", back: "internet" },
    { front: "ordinateur", back: "computer" },
    { front: "tablette", back: "tablet" },
    { front: "écran", back: "screen" },
    { front: "clavier", back: "keyboard" },
    { front: "souris", back: "mouse" },
    { front: "batterie", back: "battery" },
    { front: "chargeur", back: "charger" },
    { front: "connexion", back: "connection" },
    { front: "site", back: "website" },
    { front: "application", back: "app" },
    { front: "programme", back: "program" },
    { front: "code", back: "code" },
    { front: "données", back: "data" },
    { front: "utilisateur", back: "user" },
    { front: "mot de passe", back: "password" },
    { front: "compte", back: "account" },
    { front: "serveur", back: "server" },
    { front: "réseau", back: "network" },
    { front: "sécurité", back: "security" },
    { front: "protéger", back: "to protect" },
    { front: "pirater", back: "to hack" },
    { front: "moteur de recherche", back: "search engine" },
    { front: "site web", back: "website" },
    { front: "navigateur", back: "browser" },
    { front: "télécharger", back: "to download" },
    { front: "téléverser", back: "to upload" },
    { front: "installer", back: "to install" },
    { front: "désinstaller", back: "to uninstall" },
    { front: "mettre à jour", back: "to update" },
    { front: "version", back: "version" },
    { front: "dépannage", back: "troubleshooting" },
    { front: "bug", back: "bug" },
    { front: "erreur", back: "error" },
    { front: "problème", back: "problem" },
    { front: "solution", back: "solution" },
    { front: "mise à jour", back: "update" },
    { front: "fonction", back: "function" },
    { front: "langage", back: "language" },
    { front: "interface", back: "interface" },
    { front: "application", back: "application" },
    { front: "serveur", back: "server" },
    { front: "base de données", back: "database" },
    { front: "requête", back: "query" },
    { front: "réponse", back: "response" },
    { front: "serveur web", back: "web server" },
    { front: "page web", back: "web page" },
    { front: "compte utilisateur", back: "user account" },
    { front: "connexion", back: "login" },
    { front: "déconnexion", back: "logout" },
    { front: "authentification", back: "authentication" },
    { front: "mot de passe", back: "password" },
    { front: "inscription", back: "sign up" },
    { front: "connexion", back: "login" },
    { front: "compte", back: "account" },
    { front: "connexion", back: "connect" },
    { front: "réseau social", back: "social network" },
    { front: "profil", back: "profile" },
    { front: "message", back: "message" },
    { front: "commentaire", back: "comment" },
    { front: "publication", back: "post" },
    { front: "like", back: "like" },
    { front: "partager", back: "to share" },
    { front: "suivre", back: "to follow" },
    { front: "abonné", back: "follower" },
    { front: "abonnement", back: "subscription" },
    { front: "fonctionnalité", back: "feature" },
    { front: "réglage", back: "setting" },
    { front: "option", back: "option" },
    { front: "système", back: "system" },
    { front: "fonction", back: "function" },
    { front: "exécuter", back: "to execute" },
    { front: "traiter", back: "to process" },
    { front: "demander", back: "to request" },
    { front: "répondre", back: "to reply" },
    { front: "notification", back: "notification" },
    { front: "alerte", back: "alert" },
    { front: "configuration", back: "configuration" },
    { front: "sauvegarde", back: "backup" },
    { front: "restaurer", back: "to restore" },
    { front: "fichier", back: "file" },
    { front: "dossier", back: "folder" },
    { front: "télécharger", back: "to download" },
    { front: "importer", back: "to import" },
    { front: "exporter", back: "to export" },
    { front: "partager", back: "to share" },
    { front: "envoyer", back: "to send" },
    { front: "recevoir", back: "to receive" },
    { front: "ouvrir", back: "to open" },
    { front: "fermer", back: "to close" },
    { front: "modifier", back: "to edit" },
    { front: "annuler", back: "to cancel" },
    { front: "appliquer", back: "to apply" },
    { front: "réinitialiser", back: "to reset" },
    { front: "enregistrer", back: "to save" },
    { front: "supprimer", back: "to delete" },
    { front: "activer", back: "to activate" },
    { front: "désactiver", back: "to deactivate" },
    { front: "trier", back: "to sort" },
    { front: "filtrer", back: "to filter" },
    { front: "chercher", back: "to search" },
    { front: "afficher", back: "to display" },
    { front: "masquer", back: "to hide" },
    { front: "réduire", back: "to minimize" },
    { front: "agrandir", back: "to maximize" },
    { front: "télécharger", back: "to download" },
    { front: "téléverser", back: "to upload" },
    { front: "synchrone", back: "synchronous" },
    { front: "asynchrone", back: "asynchronous" },
    { front: "échec", back: "failure" },
    { front: "succès", back: "success" },
    { front: "erreur", back: "error" },
    { front: "progrès", back: "progress" },
    { front: "statistique", back: "statistic" },
    { front: "analyse", back: "analysis" },
    { front: "résultats", back: "results" },
    { front: "graphique", back: "graph" },
    { front: "rapport", back: "report" },
    { front: "tableau", back: "table" },
    { front: "trouver", back: "to find" },
    { front: "identifier", back: "to identify" },
    { front: "évaluer", back: "to evaluate" },
    { front: "tester", back: "to test" },
    { front: "analyser", back: "to analyze" },
    { front: "comparer", back: "to compare" },
    { front: "valider", back: "to validate" }
];


module.exports = frechWords;